version: "3.8"

services:
  app:
    container_name: react-frontend
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '4040:80'
    environment: 
      NODE_ENV: production